env:
  global:
  - ENCRYPTION_LABEL: "bdeaeb305a10"
  - COMMIT_AUTHOR_EMAIL: "travis@travis.com"
matrix:
  include:
    - os: linux
      language: generic
      env: PYTHON_VERSION=3.5
    - os: linux
      language: generic
      env: PYTHON_VERSION=3.6
before_install:
  - ./.travis/install.sh
install:
  - PATH="$HOME/miniconda/bin:$PATH" flake8 .
  - PATH="$HOME/miniconda/bin:$PATH" pip install -e .

after_success:
    - PATH="$HOME/miniconda/bin:$PATH" ./.travis/docs.sh
